version: "3"
services:
    db:
        # 指定 mysql 5.7 版本镜像
        image: mysql:5.7
        volumes:
            - ./data:/var/lib/mysql:rw
            - ./log/mysql:/var/log/mysql:rw
            - ./conf/mysql:/etc/mysql/conf.d:ro
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker_mysql_connect
            MYSQL_DATABASE: dockerdb
        container_name: mysql
        networks:
            - net-db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        container_name: phpmyadmin
        networks:
            - net-db
        depends_on:
            - db
    php:
        # image: php:7.4-fpm
        build: ./build/php
        volumes:
            - ./www:/var/www:rw
            - ./conf/php/php-fpm/php-fpm.conf:/usr/loca/etc/php-fpm.conf:ro
            - ./conf/php/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d:ro
            - ./conf/php/php/php.ini:/usr/local/etc/php/php.ini:ro
        # 暴露容器的 9000 端口，但不进行映射
        expose:
            - "9000"
        container_name: php-fpm
        networks:
            - net-db
            - net-web
    nginx:
        image: nginx:1.17.8
        volumes:
            - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./log/nginx:/var/log/nginx:rw
            - ./www:/var/www:rw
        ports:
            - "80:80"
            - "443:443"
        container_name: nginx
        networks:
            - net-web
            - net-db
        depends_on:
            - db
            - php
networks:
    net-db:
    net-web:
